---@enum WeaponClass
local weaponClasses = { -- Define gta weapon classe numbers
    SMALL_CALIBER = 1,
    MEDIUM_CALIBER = 2,
    HIGH_CALIBER = 3,
    SHOTGUN = 4,
    CUTTING = 5,
    LIGHT_IMPACT = 6,
    HEAVY_IMPACT = 7,
    EXPLOSIVE = 8,
    FIRE = 9,
    SUFFOCATING = 10,
    OTHER = 11,
    WILDLIFE = 12,
    NONE = 13,
}

return {
    weaponClasses = weaponClasses,
    fadeOutTimer = 2, -- How many bleed ticks occur before fadeout happens
    blackoutTimer = 10, -- How many bleed ticks occur before blacking out
    bleedDamageTimer = 8, -- The base damage that is multiplied by bleed level everytime a bleed tick occurs
    advanceBleedTimer = 10, -- How many bleed ticks occur before bleed level increases
    bleedTickRate = 30, -- How much time, in seconds, between bleed ticks
    bleedMovementTick = 10, -- How many seconds is taken away from the bleed tick rate if the player is walking, jogging, or sprinting
    bleedMovementAdvance = 3, -- How much time moving while bleeding adds
    armorDamage = 5, -- Minumum damage done to armor before checking for injuries
    messageTimer = 12, -- How long it will take to display limb/bleed message
    alertShowInfo = 2, -- How many injuries a player must have before being alerted about them
    headInjuryTimer = 30, -- How much time, in seconds, do head injury effects chance occur
    armInjuryTimer = 30, -- How much time, in seconds, do arm injury effects chance occur
    legInjuryTimer = 15, -- How much time, in seconds, do leg injury effects chance occur
    headInjuryChance = 25, -- The chance, in percent, that head injury side-effects get applied
    legInjuryChance = { -- The chance, in percent, that leg injury side-effects get applied
        running = 50,
        walking = 15,
    },
    laststandReviveInterval = 360,

    forceInjury = 35, -- Maximum amount of damage a player can take before limb damage & effects are forced to occur
    healthDamage = 5, -- Minimum damage done to health before checking for injuries
    maxInjuryChanceMulti = 3, -- Maximum chance of an injury from damage above healthDamage
    forceInjuryWeapons = { -- Define which weapons will always cause injuries
        [weaponClasses.HIGH_CALIBER] = true,
        [weaponClasses.HEAVY_IMPACT] = true,
        [weaponClasses.EXPLOSIVE] = true,
    },

    criticalAreas = { -- Define body areas that will always cause bleeding if wearing armor or not
        UPPER_BODY = { armored = false },
        LOWER_BODY = { armored = true },
        SPINE = { armored = true },
    },

    ---@class StaggerArea Defined body areas that will always cause staggering if wearing armor or not
    ---@field armored boolean
    ---@field major number
    ---@field minor number
    staggerAreas = {
        SPINE = { armored = true, major = 60, minor = 30 },
        UPPER_BODY = { armored = false, major = 60, minor = 30 },
        LLEG = { armored = true, major = 100, minor = 85 },
        RLEG = { armored = true, major = 100, minor = 85 },
        LFOOT = { armored = true, major = 100, minor = 100 },
        RFOOT = { armored = true, major = 100, minor = 100 },
    },

    majorArmoredBleedChance = 45, -- The chance, in percent, that a player will get a bleed effect when taking heavy damage while wearing armor
    minorInjurWeapons = { -- Define which weapons cause small injuries
        [weaponClasses.SMALL_CALIBER] = true,
        [weaponClasses.MEDIUM_CALIBER] = true,
        [weaponClasses.CUTTING] = true,
        [weaponClasses.WILDLIFE] = true,
        [weaponClasses.OTHER] = true,
        [weaponClasses.LIGHT_IMPACT] = true,
    },

    majorInjurWeapons = { -- Define which weapons cause large injuries
        [weaponClasses.HIGH_CALIBER] = true,
        [weaponClasses.HEAVY_IMPACT] = true,
        [weaponClasses.SHOTGUN] = true,
        [weaponClasses.EXPLOSIVE] = true,
    },

    damageMinorToMajor = 35, -- How much damage would have to be applied for a minor weapon to be considered a major damage event. Put this at 100 if you want to disable it
    alwaysBleedChanceWeapons = { -- Define which weapons will always cause bleedign
        [weaponClasses.SMALL_CALIBER] = true,
        [weaponClasses.MEDIUM_CALIBER] = true,
        [weaponClasses.CUTTING] = true,
        [weaponClasses.WILDLIFE] = false,
    },
    
    alwaysBleedChance = 70, -- Set the chance out of 100 that if a player is hit with a weapon, that also has a random chance, it will cause bleeding

    ---@type table<number, string>
    bones = { -- Correspond bone hash numbers to their label
		[0] = 'SKEL_ROOT',
		[11816] = 'SKEL_Pelvis',
		[58271] = 'SKEL_L_Thigh',
		[63931] = 'SKEL_L_Calf',
		[14201] = 'SKEL_L_Foot',
		[2108]  = 'SKEL_L_Toe0',
		[65245] = 'EO_L_Foot',
		[35502] = 'EO_L_Toe',
		[35502] = 'IK_L_Foot',
		[57717] = 'PH_L_Foot',
		[46078] = 'MH_L_Knee',
		[51826] = 'SKEL_R_Thigh',
		[36864] = 'SKEL_R_Calf',
		[52301] = 'SKEL_R_Foot',
		[20781] = 'SKEL_R_Toe0',
		[65245] = 'EO_R_Foot',
		[35502] = 'EO_R_Toe',
		[35502] = 'IK_R_Foot',
		[57717] = 'PH_R_Foot',
		[16335] = 'MH_R_Knee',
		[23639] = 'RB_L_ThighRoll',
		[23639] = 'RB_R_ThighRoll',
		[57597] = 'SKEL_Spine_Root',
		[23553] = 'SKEL_Spine0',
		[24816] = 'SKEL_Spine1',
		[24817] = 'SKEL_Spine2',
		[24818] = 'SKEL_Spine3',
		[64729] = 'SKEL_L_Clavicle',
		[45509] = 'SKEL_L_UpperArm',
		[61163] = 'SKEL_L_Forearm',
		[18905] = 'SKEL_L_Hand',
		[26610] = 'SKEL_L_Finger00',
		[4089]  = 'SKEL_L_Finger01',
		[4090]  = 'SKEL_L_Finger02',
		[26611] = 'SKEL_L_Finger10',
		[4169]  = 'SKEL_L_Finger11',
		[4170]  = 'SKEL_L_Finger12',
		[26612] = 'SKEL_L_Finger20',
		[4185]  = 'SKEL_L_Finger21',
		[4186]  = 'SKEL_L_Finger22',
		[26613] = 'SKEL_L_Finger30',
		[4137]  = 'SKEL_L_Finger31',
		[4138]  = 'SKEL_L_Finger32',
		[26614] = 'SKEL_L_Finger40',
		[4153]  = 'SKEL_L_Finger41',
		[4154]  = 'SKEL_L_Finger42',
		[60309] = 'PH_L_Hand',
		[36029] = 'IK_L_Hand',
		[61007] = 'RB_L_ForeArmRoll',
		[5232]  = 'RB_L_ArmRoll',
		[22711] = 'MH_L_Elbow',
		[10706] = 'SKEL_R_Clavicle',
		[40269] = 'SKEL_R_UpperArm',
		[28252] = 'SKEL_R_Forearm',
		[6286]  = 'SKEL_R_Hand',
		[58866] = 'SKEL_R_Finger00',
		[64016] = 'SKEL_R_Finger01',
		[64017] = 'SKEL_R_Finger02',
		[58867] = 'SKEL_R_Finger10',
		[64096] = 'SKEL_R_Finger11',
		[64097] = 'SKEL_R_Finger12',
		[58868] = 'SKEL_R_Finger20',
		[64112] = 'SKEL_R_Finger21',
		[64113] = 'SKEL_R_Finger22',
		[58869] = 'SKEL_R_Finger30',
		[64064] = 'SKEL_R_Finger31',
		[64065] = 'SKEL_R_Finger32',
		[58870] = 'SKEL_R_Finger40',
		[64080] = 'SKEL_R_Finger41',
		[64081] = 'SKEL_R_Finger42',
		[28422] = 'PH_R_Hand',
		[6286]  = 'IK_R_Hand',
		[61007] = 'RB_R_ForeArmRoll',
		[5232]  = 'RB_R_ArmRoll',
		[2992]  = 'MH_R_Elbow',
		[39317] = 'SKEL_Neck_1',
		[31086] = 'SKEL_Head',
		[12844] = 'IK_Head',
		[65068] = 'FACIAL_facialRoot',
		[58331] = 'FB_L_Brow_Out_000',
		[45750] = 'FB_L_Lid_Upper_000',
		[25260] = 'FB_L_Eye_000',
		[21550] = 'FB_L_CheekBone_000',
		[29868] = 'FB_L_Lip_Corner_000',
		[33646] = 'FB_R_Lid_Upper_000',
		[25260] = 'FB_R_Eye_000',
		[21550] = 'FB_R_CheekBone_000',
		[58331] = 'FB_R_Brow_Out_000',
		[29868] = 'FB_R_Lip_Corner_000',
		[58331] = 'FB_Brow_Centre_000',
		[36011] = 'FB_UpperLipRoot_000',
		[32258] = 'FB_UpperLip_000',
		[42095] = 'FB_L_Lip_Top_000',
		[39360] = 'FB_R_Lip_Top_000',
		[46240] = 'FB_Jaw_000',
		[17188] = 'FB_LowerLipRoot_000',
		[20623] = 'FB_LowerLip_000',
		[47419] = 'FB_L_Lip_Bot_000',
		[49983] = 'FB_R_Lip_Bot_000',
		[47495] = 'FB_Tongue_000';
		[31086] = 'RB_Neck_1',
		[10985] = 'SPR_L_Breast',
		[14173] = 'SPR_R_Breast',
		[25532] = 'IK_Root',
		[37119] = 'SKEL_Neck_2',
		[37552] = 'SKEL_Pelvis1',
		[9442]  = 'SKEL_PelvisRoot',
		[15867] = 'SKEL_SADDLE',
		[36864] = 'MH_L_CalfBack',
		[63728] = 'MH_L_ThighBack',
		[64596] = 'SM_L_Skirt',
		[36864] = 'MH_R_CalfBack',
		[63728] = 'MH_R_ThighBack',
		[64596] = 'SM_R_Skirt',
		[14165] = 'SM_M_BackSkirtRoll',
		[14166] = 'SM_L_BackSkirtRoll',
		[14167] = 'SM_R_BackSkirtRoll',
		[14168] = 'SM_M_FrontSkirtRoll',
		[14169] = 'SM_L_FrontSkirtRoll',
		[14170] = 'SM_R_FrontSkirtRoll',
		[4019]  = 'SM_CockNBalls_ROOT',
		[4586]  = 'SM_CockNBalls',
		[26610] = 'MH_L_Finger00',
		[10000] = 'MH_L_FingerBulge00',
		[26611] = 'MH_L_Finger10',
		[64768] = 'MH_L_FingerTop00',
		[45722] = 'MH_L_HandSide',
		[4319]  = 'MH_Watch',
		[64486] = 'MH_L_Sleeve',
		[58866] = 'MH_R_Finger00',
		[10000] = 'MH_R_FingerBulge00',
		[58867] = 'MH_R_Finger10',
		[43810] = 'MH_R_FingerTop00',
		[28252] = 'MH_R_HandSide',
		[13349] = 'MH_R_Sleeve',
		[46240] = 'FACIAL_jaw',
		[47419] = 'FACIAL_underChin',
		[37706] = 'FACIAL_L_underChin',
		[2622]  = 'FACIAL_chin',
		[5456]  = 'FACIAL_chinSkinBottom',
		[5404]  = 'FACIAL_L_chinSkinBottom',
		[5405]  = 'FACIAL_R_chinSkinBottom',
		[3844]  = 'FACIAL_tongueA',
		[3845]  = 'FACIAL_tongueB',
		[3846]  = 'FACIAL_tongueC',
		[3847]  = 'FACIAL_tongueD',
		[3848]  = 'FACIAL_tongueE',
		[3849]  = 'FACIAL_L_tongueE',
		[3850]  = 'FACIAL_R_tongueE',
		[3851]  = 'FACIAL_L_tongueD',
		[3852]  = 'FACIAL_R_tongueD',
		[3853]  = 'FACIAL_L_tongueC',
		[3854]  = 'FACIAL_R_tongueC',
		[3855]  = 'FACIAL_L_tongueB',
		[3856]  = 'FACIAL_R_tongueB',
		[3857]  = 'FACIAL_L_tongueA',
		[3858]  = 'FACIAL_R_tongueA',
		[5691]  = 'FACIAL_chinSkinTop',
		[5689]  = 'FACIAL_L_chinSkinTop',
		[5690]  = 'FACIAL_chinSkinMid',
		[5690]  = 'FACIAL_L_chinSkinMid',
		[4772]  = 'FACIAL_L_chinSide',
		[4773]  = 'FACIAL_R_chinSkinMid',
		[4774]  = 'FACIAL_R_chinSkinTop',
		[4775]  = 'FACIAL_R_chinSide',
		[4850]  = 'FACIAL_R_underChin',
		[6286]  = 'FACIAL_L_lipLowerSDK',
		[5855]  = 'FACIAL_L_lipLowerAnalog',
		[6279]  = 'FACIAL_L_lipLowerThicknessV',
		[6028]  = 'FACIAL_L_lipLowerThicknessH',
		[47505] = 'FACIAL_lipLowerSDK',
		[57005] = 'FACIAL_lipLowerAnalog',
		[46504] = 'FACIAL_lipLowerThicknessV',
		[47503] = 'FACIAL_lipLowerThicknessH',
		[5643]  = 'FACIAL_R_lipLowerSDK',
		[5292]  = 'FACIAL_R_lipLowerAnalog',
		[5625]  = 'FACIAL_R_lipLowerThicknessV',
		[5473]  = 'FACIAL_R_lipLowerThicknessH',
		[41263] = 'FACIAL_nose',
		[5010]  = 'FACIAL_L_nostril',
		[5291]  = 'FACIAL_L_nostrilThickness',
		[10439] = 'FACIAL_noseLower',
		[9845]  = 'FACIAL_L_noseLowerThickness',
		[11307] = 'FACIAL_R_noseLowerThickness',
		[11817] = 'FACIAL_noseTip',
		[45631] = 'FACIAL_R_nostril',
		[4476]  = 'FACIAL_R_nostrilThickness',
		[2690]  = 'FACIAL_noseUpper',
		[3031]  = 'FACIAL_L_noseUpper',
		[16128] = 'FACIAL_noseBridge',
		[34087] = 'FACIAL_L_nasolabialFurrow',
		[24356] = 'FACIAL_L_nasolabialBulge',
		[24903] = 'FACIAL_L_cheekLower',
		[34748] = 'FACIAL_L_cheekLowerBulge1',
		[34749] = 'FACIAL_L_cheekLowerBulge2',
		[14850] = 'FACIAL_L_cheekInner',
		[4013]  = 'FACIAL_L_cheekOuter',
		[64768] = 'FACIAL_L_eyesackLower',
		[5868]  = 'FACIAL_L_eyeball',
		[61007] = 'FACIAL_L_eyelidLower';
		[4693]  = 'FACIAL_L_eyelidLowerOuterSDK',
		[4998] = 'FACIAL_L_eyelidLowerOuterAnalog',
		[1477] = 'FACIAL_L_eyelashLowerOuter',
		[1411] = 'FACIAL_L_eyelidLowerInnerSDK',
		[1152] = 'FACIAL_L_eyelidLowerInnerAnalog',
		[1584] = 'FACIAL_L_eyelashLowerInner',
		[5888] = 'FACIAL_L_eyelidUpper',
		[6094] = 'FACIAL_L_eyelidUpperOuterSDK',
		[6210] = 'FACIAL_L_eyelidUpperOuterAnalog',
		[5750] = 'FACIAL_L_eyelashUpperOuter',
		[6306] = 'FACIAL_L_eyelidUpperInnerSDK',
		[6422] = 'FACIAL_L_eyelidUpperInnerAnalog',
		[6478] = 'FACIAL_L_eyelashUpperInner',
		[5753] = 'FACIAL_L_eyesackUpperOuterBulge',
		[5859] = 'FACIAL_L_eyesackUpperInnerBulge',
		[5965] = 'FACIAL_L_eyesackUpperOuterFurrow',
		[6071] = 'FACIAL_L_eyesackUpperInnerFurrow',
		[5769] = 'FACIAL_forehead',
		[4317] = 'FACIAL_L_foreheadInner',
		[5201] = 'FACIAL_L_foreheadInnerBulge',
		[4779] = 'FACIAL_L_foreheadOuter',
		[5589] = 'FACIAL_skull',
		[1243] = 'FACIAL_foreheadUpper',
		[2826] = 'FACIAL_L_foreheadUpperInner',
		[2609] = 'FACIAL_L_foreheadUpperOuter',
		[1803] = 'FACIAL_R_foreheadUpperInner',
		[1586] = 'FACIAL_R_foreheadUpperOuter',
		[6426] = 'FACIAL_L_temple',
		[26819] = 'FACIAL_L_ear',
		[27695] = 'FACIAL_L_earLower',
		[4966] = 'FACIAL_L_masseter',
		[5478] = 'FACIAL_L_jawRecess',
		[6308] = 'FACIAL_L_cheekOuterSkin',
		[25482] = 'FACIAL_R_cheekLower',
		[13078] = 'FACIAL_R_cheekLowerBulge1',
		[13079] = 'FACIAL_R_cheekLowerBulge2',
		[4614] = 'FACIAL_R_masseter',
		[5126] = 'FACIAL_R_jawRecess',
		[21815] = 'FACIAL_R_ear',
		[25552] = 'FACIAL_R_earLower',
		[3980] = 'FACIAL_R_eyesackLower',
		[1150] = 'FACIAL_R_nasolabialBulge',
		[2538] = 'FACIAL_R_cheekOuter',
		[1894] = 'FACIAL_R_cheekInner',
		[6123] = 'FACIAL_R_noseUpper',
		[5768] = 'FACIAL_R_foreheadInner',
		[5054] = 'FACIAL_R_foreheadInnerBulge',
		[5338] = 'FACIAL_R_foreheadOuter',
		[6354] = 'FACIAL_R_cheekOuterSkin',
		[6522] = 'FACIAL_R_eyesackUpperInnerFurrow',
		[6523] = 'FACIAL_R_eyesackUpperOuterFurrow',
		[6524] = 'FACIAL_R_eyesackUpperInnerBulge',
		[6525] = 'FACIAL_R_eyesackUpperOuterBulge',
		[2755] = 'FACIAL_R_nasolabialFurrow',
		[6100] = 'FACIAL_R_temple',
		[35063] = 'FACIAL_R_eyeball',
		[29317] = 'FACIAL_R_eyelidUpper',
		[30109] = 'FACIAL_R_eyelidUpperOuterSDK',
		[30065] = 'FACIAL_R_eyelidUpperOuterAnalog',
		[29651] = 'FACIAL_R_eyelashUpperOuter',
		[29821] = 'FACIAL_R_eyelidUpperInnerSDK',
		[29695] = 'FACIAL_R_eyelidUpperInnerAnalog',
		[29569] = 'FACIAL_R_eyelashUpperInner',
		[33436] = 'FACIAL_R_eyelidLower',
		[33348] = 'FACIAL_R_eyelidLowerOuterSDK',
		[33346] = 'FACIAL_R_eyelidLowerOuterAnalog',
		[33344] = 'FACIAL_R_eyelashLowerOuter',
		[33516] = 'FACIAL_R_eyelidLowerInnerSDK',
		[33458] = 'FACIAL_R_eyelidLowerInnerAnalog',
		[33422] = 'FACIAL_R_eyelashLowerInner',
		[7392] = 'FACIAL_L_lipUpperSDK',
		[7679] = 'FACIAL_L_lipUpperAnalog',
		[7541] = 'FACIAL_L_lipUpperThicknessH',
		[7338] = 'FACIAL_L_lipUpperThicknessV',
		[7815] = 'FACIAL_lipUpperSDK',
		[7777] = 'FACIAL_lipUpperAnalog',
		[7801] = 'FACIAL_lipUpperThicknessH',
		[7793] = 'FACIAL_lipUpperThicknessV',
		[7923] = 'FACIAL_L_lipCornerSDK',
		[8100] = 'FACIAL_L_lipCornerAnalog',
		[8256] = 'FACIAL_L_lipCornerThicknessUpper',
		[8254] = 'FACIAL_L_lipCornerThicknessLower',
		[7977] = 'FACIAL_R_lipUpperSDK',
		[8083] = 'FACIAL_R_lipUpperAnalog',
		[7985] = 'FACIAL_R_lipUpperThicknessH',
		[8033] = 'FACIAL_R_lipUpperThicknessV',
		[8128] = 'FACIAL_R_lipCornerSDK',
		[8271] = 'FACIAL_R_lipCornerAnalog',
		[8359] = 'FACIAL_R_lipCornerThicknessUpper',
		[8361] = 'FACIAL_R_lipCornerThicknessLower',
		[10210] = 'MH_MulletRoot',
		[29838] = 'MH_MulletScaler',
		[7535] = 'MH_Hair_Scale',
		[3167] = 'MH_Hair_Crown',
		[4171] = 'SM_Torch',
		[22287] = 'FX_Light',
		[29414] = 'FX_Light_Scale',
		[3626] = 'FX_Light_Switch',
		[29416] = 'BagRoot',
		[33033] = 'BagPivotROOT',
		[29823] = 'BagPivot',
		[5452] = 'BagBody',
		[23517] = 'BagBone_R',
		[24887] = 'BagBone_L',
		[30986] = 'SM_LifeSaver_Front',
		[24863] = 'SM_R_Pouches_ROOT',
		[12325] = 'SM_R_Pouches',
		[23731] = 'SM_L_Pouches_ROOT',
		[13547] = 'SM_L_Pouches',
		[19559] = 'SM_Suit_Back_Flapper',
		[27817] = 'SPR_CopRadio',
		[37318] = 'SM_LifeSaver_Back',
		[14857] = 'MH_BlushSlider',
		[35224] = 'SKEL_Tail_01',
		[35225] = 'SKEL_Tail_02',
		[12641] = 'MH_L_Concertina_B',
		[16931] = 'MH_L_Concertina_A',
		[12641] = 'MH_R_Concertina_B',
		[16931] = 'MH_R_Concertina_A',
		[39317] = 'MH_L_ShoulderBladeRoot',
		[38791] = 'MH_L_ShoulderBlade',
		[39317] = 'MH_R_ShoulderBladeRoot',
		[38791] = 'MH_R_ShoulderBlade',
		[27865] = 'FB_R_Ear_000',
		[28431] = 'SPR_R_Ear',
		[27864] = 'FB_L_Ear_000',
		[28432] = 'SPR_L_Ear',
		[23635] = 'FB_TongueA_000',
		[23636] = 'FB_TongueB_000',
		[23637] = 'FB_TongueC_000',
		[14201] = 'SKEL_L_Toe1',
		[11320] = 'SKEL_R_Toe1',
		[35226] = 'SKEL_Tail_03',
		[35227] = 'SKEL_Tail_04',
		[35228] = 'SKEL_Tail_05',
		[2633] = 'SPR_Gonads_ROOT',
		[6217] = 'SPR_Gonads',
		[1356] = 'FB_L_Brow_Out_001',
		[1998] = 'FB_L_Lid_Upper_001',
		[2563] = 'FB_L_Eye_001',
		[1463] = 'FB_L_CheekBone_001',
		[6478] = 'FB_L_Lip_Corner_001',
		[4642] = 'FB_R_Lid_Upper_001',
		[6031] = 'FB_R_Eye_001',
		[2659] = 'FB_R_CheekBone_001',
		[3681] = 'FB_R_Brow_Out_001',
		[8704] = 'FB_R_Lip_Corner_001',
		[6781] = 'FB_Brow_Centre_001',
		[6735] = 'FB_UpperLipRoot_001',
		[8002] = 'FB_UpperLip_001',
		[5730] = 'FB_L_Lip_Top_001',
		[5892] = 'FB_R_Lip_Top_001',
		[3773] = 'FB_Jaw_001',
		[6886] = 'FB_LowerLipRoot_001',
		[5161] = 'FB_LowerLip_001',
		[5161] = 'FB_L_Lip_Bot_001',
		[8414] = 'FB_R_Lip_Bot_001',
		[5832] = 'FB_Tongue_001';
    },

    weapons = { -- Correspond weapon names to their class number
        [`WEAPON_STUNGUN`] = weaponClasses.NONE,
        [`WEAPON_STUNGUN_MP`] = weaponClasses.NONE,
        --[[ Small Caliber ]] --
        [`WEAPON_PISTOL`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_COMBATPISTOL`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_APPISTOL`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_COMBATPDW`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_MACHINEPISTOL`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_MICROSMG`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_MINISMG`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_PISTOL_MK2`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_SNSPISTOL`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_SNSPISTOL_MK2`] = weaponClasses.SMALL_CALIBER,
        [`WEAPON_VINTAGEPISTOL`] = weaponClasses.SMALL_CALIBER,

        --[[ Medium Caliber ]] --
        [`WEAPON_ADVANCEDRIFLE`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_ASSAULTSMG`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_BULLPUPRIFLE`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_BULLPUPRIFLE_MK2`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_CARBINERIFLE`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_CARBINERIFLE_MK2`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_COMPACTRIFLE`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_DOUBLEACTION`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_GUSENBERG`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_HEAVYPISTOL`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_MARKSMANPISTOL`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_PISTOL50`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_REVOLVER`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_REVOLVER_MK2`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_SMG`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_SMG_MK2`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_SPECIALCARBINE`] = weaponClasses.MEDIUM_CALIBER,
        [`WEAPON_SPECIALCARBINE_MK2`] = weaponClasses.MEDIUM_CALIBER,

        --[[ High Caliber ]] --
        [`WEAPON_ASSAULTRIFLE`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_ASSAULTRIFLE_MK2`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_COMBATMG`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_COMBATMG_MK2`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_HEAVYSNIPER`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_HEAVYSNIPER_MK2`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_MARKSMANRIFLE`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_MARKSMANRIFLE_MK2`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_MG`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_MINIGUN`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_MUSKET`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_RAILGUN`] = weaponClasses.HIGH_CALIBER,
        [`WEAPON_HEAVYRIFLE`] = weaponClasses.HIGH_CALIBER,

        --[[ Shotguns ]] --
        [`WEAPON_ASSAULTSHOTGUN`] = weaponClasses.SHOTGUN,
        [`WEAPON_BULLUPSHOTGUN`] = weaponClasses.SHOTGUN,
        [`WEAPON_DBSHOTGUN`] = weaponClasses.SHOTGUN,
        [`WEAPON_HEAVYSHOTGUN`] = weaponClasses.SHOTGUN,
        [`WEAPON_PUMPSHOTGUN`] = weaponClasses.SHOTGUN,
        [`WEAPON_PUMPSHOTGUN_MK2`] = weaponClasses.SHOTGUN,
        [`WEAPON_SAWNOFFSHOTGUN`] = weaponClasses.SHOTGUN,
        [`WEAPON_SWEEPERSHOTGUN`] = weaponClasses.SHOTGUN,

        --[[ Animals ]] --
        [`WEAPON_ANIMAL`] = weaponClasses.WILDLIFE, -- Animal
        [`WEAPON_COUGAR`] = weaponClasses.WILDLIFE, -- Cougar
        [`WEAPON_BARBED_WIRE`] = weaponClasses.WILDLIFE, -- Barbed Wire

        --[[ Cutting Weapons ]] --
        [`WEAPON_BATTLEAXE`] = weaponClasses.CUTTING,
        [`WEAPON_BOTTLE`] = weaponClasses.CUTTING,
        [`WEAPON_DAGGER`] = weaponClasses.CUTTING,
        [`WEAPON_HATCHET`] = weaponClasses.CUTTING,
        [`WEAPON_KNIFE`] = weaponClasses.CUTTING,
        [`WEAPON_MACHETE`] = weaponClasses.CUTTING,
        [`WEAPON_SWITCHBLADE`] = weaponClasses.CUTTING,

        --[[ Light Impact ]] --
        [`WEAPON_KNUCKLE`] = weaponClasses.LIGHT_IMPACT,

        --[[ Heavy Impact ]] --
        [`WEAPON_BAT`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_CROWBAR`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_FIREEXTINGUISHER`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_FIRWORK`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_GOLFLCUB`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_HAMMER`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_PETROLCAN`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_POOLCUE`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_WRENCH`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_RAMMED_BY_CAR`] = weaponClasses.HEAVY_IMPACT,
        [`WEAPON_RUN_OVER_BY_CAR`] = weaponClasses.HEAVY_IMPACT,

        --[[ Explosives ]] --
        [`WEAPON_EXPLOSION`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_GRENADE`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_COMPACTLAUNCHER`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_HOMINGLAUNCHER`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_PIPEBOMB`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_PROXMINE`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_RPG`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_STICKYBOMB`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_HELI_CRASH`] = weaponClasses.EXPLOSIVE,
        [`WEAPON_EMPLAUNCHER`] = weaponClasses.EXPLOSIVE,

        --[[ Other ]] --
        [`WEAPON_FALL`] = weaponClasses.OTHER, -- Fall
        [`WEAPON_HIT_BY_WATER_CANNON`] = weaponClasses.OTHER, -- Water Cannon

        --[[ Fire ]] --
        [`WEAPON_ELECTRIC_FENCE`] = weaponClasses.FIRE,
        [`WEAPON_FIRE`] = weaponClasses.FIRE,
        [`WEAPON_MOLOTOV`] = weaponClasses.FIRE,
        [`WEAPON_FLARE`] = weaponClasses.FIRE,
        [`WEAPON_FLAREGUN`] = weaponClasses.FIRE,

        --[[ Suffocate ]] --
        [`WEAPON_DROWNING`] = weaponClasses.SUFFOCATING, -- Drowning
        [`WEAPON_DROWNING_IN_VEHICLE`] = weaponClasses.SUFFOCATING, -- Drowning Veh
        [`WEAPON_EXHAUSTION`] = weaponClasses.SUFFOCATING, -- Exhaust
        [`WEAPON_BZGAS`] = weaponClasses.SUFFOCATING,
        [`WEAPON_SMOKEGRENADE`] = weaponClasses.SUFFOCATING,
    },
}
