return {
    -- Melee
    [`weapon_unarmed`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_dagger`] = 'Knifed / Stabbed / Eviscerated',
    [`weapon_bat`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_bottle`] = 'Knifed / Stabbed / Eviscerated',
    [`weapon_crowbar`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_flashlight`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_golfclub`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_hammer`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_hatchet`] = 'Knifed / Stabbed / Eviscerated',
    [`weapon_knuckle`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_knife`] = 'Knifed / Stabbed / Eviscerated',
    [`weapon_machete`] = 'Knifed / Stabbed / Eviscerated',
    [`weapon_switchblade`] = 'Knifed / Stabbed / Eviscerated',
    [`weapon_nightstick`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_wrench`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_battleaxe`] = 'Knifed / Stabbed / Eviscerated',
    [`weapon_poolcue`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_briefcase`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_briefcase_02`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_garbagebag`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_handcuffs`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_bread`] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered',
    [`weapon_stone_hatchet`] = 'Knifed / Stabbed / Eviscerated',

    -- Pistols
    [`weapon_pistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_pistol_mk2`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_combatpistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_appistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_stungun`] = 'Died',
    [`weapon_pistol50`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_snspistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_snspistol_mk2`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_heavypistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_vintagepistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_flaregun`] = 'Died',
    [`weapon_marksmanpistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_revolver`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_revolver_mk2`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_doubleaction`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_raypistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_ceramicpistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_navyrevolver`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_gadgetpistol`] = 'Pistoled / Blasted / Plugged / Bust a cap in',
    [`weapon_stungun_mp`] = 'Died',

    -- Submachine Guns
    [`weapon_microsmg`] = 'Riddled / Drilled / Finished / Submachine Gunned',
    [`weapon_smg`] = 'Riddled / Drilled / Finished / Submachine Gunned',
    [`weapon_smg_mk2`] = 'Riddled / Drilled / Finished / Submachine Gunned',
    [`weapon_assaultsmg`] = 'Riddled / Drilled / Finished / Submachine Gunned',
    [`weapon_combatpdw`] = 'Riddled / Drilled / Finished / Submachine Gunned',
    [`weapon_machinepistol`] = 'Riddled / Drilled / Finished / Submachine Gunned',
    [`weapon_minismg`] = 'Riddled / Drilled / Finished / Submachine Gunned',
    [`weapon_raycarbine`] = 'Riddled / Drilled / Finished / Submachine Gunned',

    -- Shotguns
    [`weapon_pumpshotgun`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_pumpshotgun_mk2`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_sawnoffshotgun`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_assaultshotgun`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_bullpupshotgun`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_musket`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_heavyshotgun`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_dbshotgun`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_autoshotgun`] = 'Devastated / Pulverized / Shotgunned',
    [`weapon_combatshotgun`] = 'Devastated / Pulverized / Shotgunned',

    -- Assault Rifles
    [`weapon_assaultrifle`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_assaultrifle_mk2`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_carbinerifle`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_carbinerifle_mk2`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_advancedrifle`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_specialcarbine`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_specialcarbine_mk2`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_bullpuprifle`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_bullpuprifle_mk2`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_compactrifle`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_militaryrifle`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_heavyrifle`] = 'Ended / Rifled / Shot down / Floored',
    [`weapon_tacticalrifle`] = 'Ended / Rifled / Shot down / Floored',

    -- Light Machine Guns
    [`weapon_mg`] = 'Machine gunned / Sprayed / Ruined',
    [`weapon_combatmg`] = 'Machine gunned / Sprayed / Ruined',
    [`weapon_combatmg_mk2`] = 'Machine gunned / Sprayed / Ruined',
    [`weapon_gusenberg`] = 'Machine gunned / Sprayed / Ruined',

    -- Sniper Rifles
    [`weapon_sniperrifle`] = 'Sniped / Picked off / Scoped',
    [`weapon_heavysniper`] = 'Sniped / Picked off / Scoped',
    [`weapon_heavysniper_mk2`] = 'Sniped / Picked off / Scoped',
    [`weapon_marksmanrifle`] = 'Sniped / Picked off / Scoped',
    [`weapon_marksmanrifle_mk2`] = 'Sniped / Picked off / Scoped',
    [`weapon_remotesniper`] = 'Sniped / Picked off / Scoped',
    [`weapon_precisionrifle`] = 'Sniped / Picked off / Scoped',

    -- Heavy Weapons
    [`weapon_rpg`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_grenadelauncher`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_grenadelauncher_smoke`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_minigun`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_firework`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_railgun`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_hominglauncher`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_compactlauncher`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_rayminigun`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_emplauncher`] = 'Died',

    -- Throwables
    [`weapon_grenade`] = 'Bombed / Exploded / Detonated / Blew up',
    [`weapon_bzgas`] = 'Died',
    [`weapon_molotov`] = 'Torched / Flambeed / Barbecued',
    [`weapon_stickybomb`] = 'Bombed / Exploded / Detonated / Blew up',
    [`weapon_proxmine`] = 'Bombed / Exploded / Detonated / Blew up',
    [`weapon_snowball`] = 'Died',
    [`weapon_pipebomb`] = 'Bombed / Exploded / Detonated / Blew up',
    [`weapon_ball`] = 'Died',
    [`weapon_smokegrenade`] = 'Died',
    [`weapon_flare`] = 'Died',

    -- Miscellaneous
    [`weapon_petrolcan`] = 'Died',
    [`gadget_parachute`] = 'Died',
    [`weapon_fireextinguisher`] = 'Died',
    [`weapon_hazardcan`] = 'Died',
    [`weapon_fertilizercan`] = 'Died',
    [`weapon_barbed_wire`] = 'Prodded',
    [`weapon_drowning`] = 'Died',
    [`weapon_drowning_in_vehicle`] = 'Died',
    [`weapon_bleeding`] = 'Bled out',
    [`weapon_electric_fence`] = 'Fried',
    [`weapon_explosion`] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated',
    [`weapon_fall`] = 'Committed suicide',
    [`weapon_exhaustion`] = 'Died',
    [`weapon_hit_by_water_cannon`] = 'Died',
    [`weapon_rammed_by_car`] = 'Flattened / Ran over / Ran down',
    [`weapon_run_over_by_car`] = 'Flattened / Ran over / Ran down',
    [`weapon_heli_crash`] = 'Helicopter Crash',
    [`weapon_fire`] = 'Torched / Flambeed / Barbecued',
    [`weapon_metaldetector`] = 'Died',

    -- Animals
    [`weapon_animal`] = 'Mauled',
    [`weapon_cougar`] = 'Mauled'
}